services:
  minio:
    image: minio/minio:latest
    container_name: lab8-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    container_name: lab8-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 admin password123;
      mc mb -p local/raw;
      mc mb -p local/warehouse;
      mc ls local;
      exit 0;
      "
